markdown: kramdown
highligher: pygments
permalink: /:title
title: Nate Shoffner
permalink: /blog/:year/:month/:title/
paginate: 3
paginate_path: /blog/page/:num
url: http://nateshoffner.com
blog_url: /blog
gems:
  - jekyll-paginate
  - jekyll-sitemap
syntax_highlighter: rouge

disqus_shortname: nateshoffner